import React from "react";
import ReactDOM from "react-dom/client";
import "./css/bootstrap.min.css";
import "./css/normalize.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";
import "./css/index.css";
import App from "./js/App";
library.add(fas, fab, far);
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
